export interface PortfolioProject {
  id: string
  title: string
  client: string
  category: 'Corporate' | 'Automotive' | 'Healthcare' | 'Industrial' | 'Education' | 'Hospitality' | 'Retail' | 'Residential'
  scope: string
  location: string
  image: string
  systemType: string
  tag: string
}

export const technocyclePortfolio: PortfolioProject[] = [
  {
    id: 'technocycle-hq',
    title: 'TechnoCycle Corporate Headquarters',
    client: 'TechnoCycle Corporation',
    category: 'Corporate',
    scope: 'Central Operations Command & Multi-Zone Inverter HVAC',
    location: 'Metro Manila, Philippines',
    image: '/portfolio/technocycle-hq.png',
    systemType: 'Multi-Zone VRF & Chilled Water Network',
    tag: 'Corporate Flagship',
  },
  {
    id: 'toyota-makati',
    title: 'Toyota Makati Commercial Center',
    client: 'Toyota Motor Philippines',
    category: 'Automotive',
    scope: 'Showroom Glass Facade & Service Bay Air Handling',
    location: 'Makati City, Metro Manila',
    image: '/portfolio/toyota-makati.png',
    systemType: 'High-Capacity Ducted Commercial VRF',
    tag: 'Commercial Dealership',
  },
  {
    id: 'honda-plant',
    title: 'Honda Manufacturing Complex',
    client: 'Honda Philippines Inc.',
    category: 'Industrial',
    scope: 'Industrial Cleanroom Air Handling & Floor Ventilation',
    location: 'Batangas Industrial Park, Philippines',
    image: '/portfolio/honda-plant.png',
    systemType: 'Precision Industrial Air Filtration & AHUs',
    tag: 'Manufacturing Plant',
  },
  {
    id: 'ts-tech',
    title: 'TS Tech Industrial Facility',
    client: 'TS Tech Philippines',
    category: 'Industrial',
    scope: 'Automotive Component Plant Climate Conditioning',
    location: 'Laguna Technopark, Philippines',
    image: '/portfolio/ts-tech.png',
    systemType: 'Industrial Heavy Duty VRF Systems',
    tag: 'Industrial Facility',
  },
  {
    id: 'yamaha-yzone',
    title: 'Yamaha YZone Flagship Center',
    client: 'Yamaha Motor Philippines',
    category: 'Retail',
    scope: 'Retail Showroom & Cafe Lounge Climate Systems',
    location: 'Ortigas Center, Metro Manila',
    image: '/portfolio/yamaha-yzone.png',
    systemType: 'Commercial Ceiling Cassette & VRF',
    tag: 'Experience Center',
  },
  {
    id: 'dlsu-henry-sy',
    title: 'Henry Sy Sr. Hall - DLSU',
    client: 'De La Salle University',
    category: 'Education',
    scope: '14-Story Eco-Friendly Academic Complex HVAC',
    location: 'Taft Avenue, Manila',
    image: '/portfolio/dlsu-henry-sy.png',
    systemType: 'Energy-Efficient Central VRF Architecture',
    tag: 'Institutional Landmark',
  },
  {
    id: 'dls-benilde',
    title: 'College of Saint Benilde Campus',
    client: 'De La Salle - College of Saint Benilde',
    category: 'Education',
    scope: 'Multi-Floor Academic Wing Air Conditioning & Ventilation',
    location: 'Malate, Manila',
    image: '/portfolio/dls-benilde.png',
    systemType: 'Ducted Multi-Split & Smart Zone Control',
    tag: 'Academic Campus',
  },
  {
    id: 'pasig-doctors',
    title: 'Pasig Doctors Medical Center',
    client: 'PDMC Healthcare Inc.',
    category: 'Healthcare',
    scope: 'Hospital Clean-Air Filtration & Central Chiller Integration',
    location: 'Pasig City, Metro Manila',
    image: '/portfolio/pasig-doctors.png',
    systemType: 'HEPA Positive Pressure & Chilled Water AHUs',
    tag: 'Tertiary Hospital',
  },
  {
    id: 'premier-medical',
    title: 'The Premier Medical Center',
    client: 'Premier Medical Corporation',
    category: 'Healthcare',
    scope: 'Inpatient Suites, ICU & Diagnostic Imaging Climate Control',
    location: 'Parañaque City, Metro Manila',
    image: '/portfolio/premier-medical.png',
    systemType: 'Medical-Grade Chilled Water Air Handling',
    tag: 'Critical Healthcare',
  },
  {
    id: 'daniel-mercado',
    title: 'Daniel O. Mercado Medical Center',
    client: 'DMMC Health Network',
    category: 'Healthcare',
    scope: 'Comprehensive Hospital Ward & Clinical Zone HVAC',
    location: 'Tanauan City, Batangas',
    image: '/portfolio/daniel-mercado.png',
    systemType: 'Cleanroom & Multi-Zone Hospital Air Network',
    tag: 'Medical Center Campus',
  },
  {
    id: 'st-paul-cavite',
    title: 'St. Paul Hospital Cavite',
    client: 'St. Paul Health System',
    category: 'Healthcare',
    scope: 'Patient Care Wings & Clinical Suites Climate Conditioning',
    location: 'Dasmariñas, Cavite',
    image: '/portfolio/st-paul-cavite.png',
    systemType: 'Sterile Filtration & Variable Capacity HVAC',
    tag: 'Regional Hospital',
  },
  {
    id: 'shell-station',
    title: 'Shell Mobility & Retail Station',
    client: 'Pilipinas Shell Petroleum',
    category: 'Retail',
    scope: 'Commercial Station & Convenience Store HVAC Network',
    location: 'South Luzon Expressway, Philippines',
    image: '/portfolio/shell-station.png',
    systemType: 'Commercial Inverter Package Units',
    tag: 'Mobility & Retail',
  },
  {
    id: 'enchanted-kingdom',
    title: 'Enchanted Kingdom Theme Park',
    client: 'Enchanted Kingdom Inc.',
    category: 'Hospitality',
    scope: 'Guest Pavilion, Arcade & Indoor Attractions Air Handling',
    location: 'Santa Rosa, Laguna',
    image: '/portfolio/enchanted-kingdom.png',
    systemType: 'High-Volume Commercial Pavilion VRF',
    tag: 'Theme Park & Attractions',
  },
  {
    id: 'smdc-residences',
    title: 'Resort Condominium Residences',
    client: 'SM Development Corporation (SMDC)',
    category: 'Residential',
    scope: 'Residential High-Rise Lobby, Gym & Club Facilities HVAC',
    location: 'Metro Manila, Philippines',
    image: '/portfolio/smdc-residences.png',
    systemType: 'Central Ducted & Multi-Split Inverter Network',
    tag: 'Luxury High-Rise',
  },
  {
    id: 'torch-restaurant',
    title: 'Torch Restaurant & Lounge',
    client: 'Torch Group',
    category: 'Hospitality',
    scope: 'Fine Dining Ambient Cooling & Commercial Kitchen Exhaust',
    location: 'Greenhills, San Juan',
    image: '/portfolio/torch-restaurant.png',
    systemType: 'Precision Temperature Control & Air Balancing',
    tag: 'Commercial Dining',
  },
  {
    id: 'morning-after',
    title: 'The Morning After Cafe',
    client: 'The Morning After Group',
    category: 'Hospitality',
    scope: 'Boutique Dining & Alfresco Transition Climate Systems',
    location: 'Solenad, Santa Rosa, Laguna',
    image: '/portfolio/morning-after.png',
    systemType: 'High-Efficiency Inverter Split Units',
    tag: 'Lifestyle Cafe',
  },
  {
    id: 'don-bosco-parish',
    title: 'St. John Bosco Parish Church',
    client: 'Salesians of Don Bosco',
    category: 'Corporate',
    scope: 'High-Ceiling Nave & Sanctuary Acoustic Climate Engineering',
    location: 'Makati City, Metro Manila',
    image: '/portfolio/don-bosco-parish.png',
    systemType: 'Low-Noise High-Displacement Air Handling',
    tag: 'Heritage Sanctuary',
  },
  {
    id: 'church-auditorium',
    title: 'Faith Fellowship Sanctuary',
    client: 'Community Assembly Center',
    category: 'Corporate',
    scope: 'Multi-Tier Auditorium & Choir Balcony Air Balancing',
    location: 'Metro Manila, Philippines',
    image: '/portfolio/church-auditorium.png',
    systemType: 'Ducted Central Air & Sound-Attenuated Diffusers',
    tag: 'Assembly Hall',
  },
]
